# ワークフロー名

name: test_chatbot

# 発火タイミング
on:
  push:
  #schedule:
    #- cron: '0 22 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          
          python -m pip install --upgrade pip
          
          pip install line-bot-sdk
      - name: Run script
        env:
          CHANNEL_ACCESS_TOKEN: "XXcFebQQMtzVY7VNsI5omhhmZ6RecRHT94ZHHm3+Q6nlo0/sUceNBqgz3RLgAwXa3HH9mr7j+Tu+xH5HU8BT3kNdXGvHTSmKQqhJrvbKeaDR6zOx0cJjdl15EFsF691QaC8oOQzHZOR0O3LHniVM2AdB04t89/1O/w1cDnyilFU="
          USER_ID: "Uaf2d5dbbe1f2d178a134ff8d6d354878"
        run: |
           python main.py
