# ワークフロー名

name: line_bot 

# 発火タイミング
on:
 push:
  #schedule:
    #- cron: '0 22 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理
    runs-on: macos-11

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v.2.3.4
        with:
          python-version: 3.9.7
      - name: Install dependencies
        run: |
          
          python -m pip install --upgrade pip
          
          pip install line-bot-sdk
      - name: Run python
       # env:
         # CHANNEL_ACCESS_TOKEN: ""
        run: |
           python /Users/naoki/Jupyter/line_bot/main.py
